package domain.validators.syntactic;

/* Generated By:JavaCC: Do not edit this line. ExpressionValidatorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionValidatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 4;
  /** RegularExpression Id. */
  int EXPRESION = 5;
  /** RegularExpression Id. */
  int VALUE = 6;
  /** RegularExpression Id. */
  int OPERATOR = 7;
  /** RegularExpression Id. */
  int LEFT_PAREN = 8;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\" \"",
    "<EXPRESION>",
    "<VALUE>",
    "<OPERATOR>",
    "\"(\"",
    "\")\"",
  };

}
